name: Packaging botocore due to merge

on:
  pull_request:
    branches:
      - next
    types:
      - closed
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'Makefile'
      - '.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  call-workflow:
    if: github.event.pull_request.merged == true
    uses: c2/gha-workflows/.github/workflows/deps-merge-packaging.yml@master
    secrets:
      AUTOMATION_PAT: ${{ secrets.AUTOMATION_PAT }}
      CONTAINER_SSH_KEY: ${{ secrets.CONTAINER_SSH_KEY }}
      CONTAINER_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
