name: Release botocore

on:
  workflow_dispatch:
    inputs:
      cloud_version:
        description: Cloud version (xx.yy)
        required: true
        type: string
      release_type:
        description: Type of release
        required: true
        type: choice
        default: rc
        options:
        - release
        - rc

jobs:
  call-workflow:
    uses: c2/gha-workflows/.github/workflows/deps-release.yml@master
    with:
      cloud_version: ${{ github.event.inputs.cloud_version }}
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit
