name: Packaging botocore due to merge

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - next
    types:
      - closed
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'Makefile'
      - '.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  call-workflow:
    if: (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    uses: c2/gha-workflows/.github/workflows/deps-merge-packaging.yml@master
    secrets: inherit
