name: Notify on workflow completion

on:
  workflow_run:
    workflows: ["Packaging botocore due to merge", "Release botocore", "Set JIRA version in issue"]
    types: [completed]

jobs:
  notify:
    uses: c2/gha-workflows/.github/workflows/send-alert.yml@master
    with:
      workflow_name: ${{ github.event.workflow_run.name }}
      workflow_conclusion: ${{ github.event.workflow_run.conclusion }}
      workflow_id: ${{ github.event.workflow_run.id }}
    secrets: inherit
